apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  clusterIP: None # Headless no singel virtual IP. DNS resolves to
                  # Individual pod IPs. Required for StatefulSet per discovery
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport