# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-1

availabilityZones:
- us-east-1a
- us-east-1b

managedNodeGroups:
- name: ng-1
  instanceType: t2.medium
  desiredCapacity: 2

iam:
  withOIDC: true

addons:
- name: aws-ebs-csi-driver