apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchlabels:
      app: myapp
      version: blue
  template:
    metadata: 
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80