apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
        - containerPort: 80