apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.3.11
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          volumeMounts:
          - name: varlog # Access node logs.
            mountPath: /var/log
          - name: varlibdockercontainers # Docker container logs.
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluent-bit-config # Mounts ConfigMap.
            mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog # Mounts host filesystem.
        hostPath:
          path: /var/log
      serviceAccountName: fluent-bit
      tolerations:
      - operator: Exists
      