apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: app
spec:
  serviceAccountName: app-sa
  restartPolicy: Always
  containers:
  - name: app
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
