apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: app 
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: app 
    image: nginx:latest
    imagePullPolicy: IfNotPresent  # Always, IfNotPresent, Never
    ports:
    - containerPort: 80
