apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: dev
spec:
  serviceAccountName: app-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: [ "sleep", "3600" ]
